BACKGROUND_COLORS = [
    ("bg-primary", "Primary"),
    ("bg-primary-subtle", "Primary subtle"),
    ("bg-secondary", "Secondary"),
    ("bg-secondary-subtle", "Secondary subtle"),
    ("bg-success", "Success"),
    ("bg-success-subtle", "Success subtle"),
    ("bg-danger", "Danger"),
    ("bg-danger-subtle", "Danger subtle"),
    ("bg-warning", "Warning"),
    ("bg-warning-subtle", "Warning subtle"),
    ("bg-info", "Info"),
    ("bg-info-subtle", "Info subtle"),
    ("bg-light", "Light"),
    ("bg-light-subtle", "Light subtle"),
    ("bg-dark", "Dark"),
    ("bg-dark-subtle", "Dark subtle"),
    ("bg-body-secondary", "Body secondary"),
    ("bg-body-tertiary", "Body tertiary"),
    ("bg-body", "Body"),
    ("bg-black", "Black"),
    ("bg-white", "White"),
    ("bg-transparent", "Transparent"),
]

TEXT_COLORS = [
    ("text-primary", "Primary"),
    ("text-primary-subtle", "Primary subtle"),
    ("text-secondary", "Secondary"),
    ("text-secondary-subtle", "Secondary subtle"),
    ("text-success", "Success"),
    ("text-success-subtle", "Success subtle"),
    ("text-danger", "Danger"),
    ("text-danger-subtle", "Danger subtle"),
    ("text-warning", "Warning"),
    ("text-warning-subtle", "Warning subtle"),
    ("text-info", "Info"),
    ("text-info-subtle", "Info subtle"),
    ("text-light", "Light"),
    ("text-light-subtle", "Light subtle"),
    ("text-dark", "Dark"),
    ("text-dark-subtle", "Dark subtle"),
    ("text-body-secondary", "Body secondary"),
    ("text-body-tertiary", "Body tertiary"),
    ("text-body", "Body"),
    ("text-black", "Black"),
    ("text-white", "White"),
    ("text-transparent", "Transparent"),
]
