# Generated by Django 5.2.5 on 2025-08-30 11:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModularPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("section", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtailmarkdown.blocks.MarkdownBlock", (), {}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("bg-primary", "Primary"),
                                        ("bg-primary-subtle", "Primary subtle"),
                                        ("bg-secondary", "Secondary"),
                                        ("bg-secondary-subtle", "Secondary subtle"),
                                        ("bg-success", "Success"),
                                        ("bg-success-subtle", "Success subtle"),
                                        ("bg-danger", "Danger"),
                                        ("bg-danger-subtle", "Danger subtle"),
                                        ("bg-warning", "Warning"),
                                        ("bg-warning-subtle", "Warning subtle"),
                                        ("bg-info", "Info"),
                                        ("bg-info-subtle", "Info subtle"),
                                        ("bg-light", "Light"),
                                        ("bg-light-subtle", "Light subtle"),
                                        ("bg-dark", "Dark"),
                                        ("bg-dark-subtle", "Dark subtle"),
                                        ("bg-body-secondary", "Body secondary"),
                                        ("bg-body-tertiary", "Body tertiary"),
                                        ("bg-body", "Body"),
                                        ("bg-black", "Black"),
                                        ("bg-white", "White"),
                                        ("bg-transparent", "Transparent"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("content", 0), ("bg_color", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
