# Generated by Django 5.2.5 on 2025-08-30 12:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modular", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modularpage",
            name="content",
        ),
        migrations.AddField(
            model_name="modularpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("markdown_section", 3), ("html_section", 5), ("richtext_section", 7)],
                blank=True,
                block_lookup={
                    0: ("wagtailmarkdown.blocks.MarkdownBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bg-primary", "Primary"),
                                ("bg-primary-subtle", "Primary subtle"),
                                ("bg-secondary", "Secondary"),
                                ("bg-secondary-subtle", "Secondary subtle"),
                                ("bg-success", "Success"),
                                ("bg-success-subtle", "Success subtle"),
                                ("bg-danger", "Danger"),
                                ("bg-danger-subtle", "Danger subtle"),
                                ("bg-warning", "Warning"),
                                ("bg-warning-subtle", "Warning subtle"),
                                ("bg-info", "Info"),
                                ("bg-info-subtle", "Info subtle"),
                                ("bg-light", "Light"),
                                ("bg-light-subtle", "Light subtle"),
                                ("bg-dark", "Dark"),
                                ("bg-dark-subtle", "Dark subtle"),
                                ("bg-body-secondary", "Body secondary"),
                                ("bg-body-tertiary", "Body tertiary"),
                                ("bg-body", "Body"),
                                ("bg-black", "Black"),
                                ("bg-white", "White"),
                                ("bg-transparent", "Transparent"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text-primary", "Primary"),
                                ("text-primary-subtle", "Primary subtle"),
                                ("text-secondary", "Secondary"),
                                ("text-secondary-subtle", "Secondary subtle"),
                                ("text-success", "Success"),
                                ("text-success-subtle", "Success subtle"),
                                ("text-danger", "Danger"),
                                ("text-danger-subtle", "Danger subtle"),
                                ("text-warning", "Warning"),
                                ("text-warning-subtle", "Warning subtle"),
                                ("text-info", "Info"),
                                ("text-info-subtle", "Info subtle"),
                                ("text-light", "Light"),
                                ("text-light-subtle", "Light subtle"),
                                ("text-dark", "Dark"),
                                ("text-dark-subtle", "Dark subtle"),
                                ("text-body-secondary", "Body secondary"),
                                ("text-body-tertiary", "Body tertiary"),
                                ("text-body", "Body"),
                                ("text-black", "Black"),
                                ("text-white", "White"),
                                ("text-transparent", "Transparent"),
                            ]
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 0), ("bg_color", 1), ("text_color", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 4), ("bg_color", 1), ("text_color", 2)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 6), ("bg_color", 1), ("text_color", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
