# Generated by Django 5.2.5 on 2025-08-28 12:56

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "links",
                    wagtail.fields.StreamField(
                        [("link", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Icon name or CSS class",
                                    "required": True,
                                },
                            ),
                            2: ("wagtail.blocks.URLBlock", (), {"required": True}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 0), ("icon", 1), ("url", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
